const EXPIRED_COOKIE = 'Your session has expired. Please log in again.',
    SOMETHING_HAPPENED = 'Oops 😕, Something went wrong',
    USER_ALREADY_EXISTS = 'This email is already registered', PASSWORDS_NOT_MATCHING = 'Passwords do not match',
    LOGIN_WRONG_CREDENTIALS = 'Oops 😕, The password or email you entered is incorrect, please try again.',
    USER_REGISTERED_SUCCESSFULLY = 'You have successfully registered 😃',
    LOGIN_USER_NOT_FOUND = 'Email not found, please try again or sign up for a new account.',
    NONE = '', THIRTY_SECONDS = 30 * 1000, USER_KEY_IN_COOKIES = 'user', INVALID = 400, UNAUTHORIZED = 401,
    SERVER_STATUS_CODE = 500, LOGIN_ERROR = 'error while login', REGISTER_ERROR = 'error while register',
    PARAMETERS_MISSING = 'Bad request - missing parameters',
    CREATE_USER_ERROR = 'error while creating user', HOME_PAGE_ERROR = 'error while getting home page',
    EXPIRED_SESSION = EXPIRED_COOKIE,
    DISCONNECTED_RESPONSE = {message: EXPIRED_SESSION, url: '/'},
    DB_ERROR = 'Something went wrong with the database.',
    IMAGE_NOT_FOUND = 'No image not found', COMMENT_NOT_FOUND = 'No comments found',
    IMAGE_CREATED_FAILED = 'Image not created or found', COMMENT_CREATION_FAILED = 'Comment not created',
    ALREADY_DELETED = 'Comment already deleted', NOT_AUTHORIZED = 'You are not allowed to delete this comment',
    NO_UPDATES = 'No updates were made',
    // ==================== status codes ====================
    NOT_FOUND = 404, SERVER_ERROR = 500, UPDATE_SECONDS = 15000;

module.exports = {
    EXPIRED_COOKIE,
    SOMETHING_HAPPENED,
    USER_ALREADY_EXISTS,
    PASSWORDS_NOT_MATCHING,
    LOGIN_WRONG_CREDENTIALS,
    USER_REGISTERED_SUCCESSFULLY,
    LOGIN_USER_NOT_FOUND,
    NONE, THIRTY_SECONDS,
    USER_KEY_IN_COOKIES,
    UNAUTHORIZED, SERVER_STATUS_CODE,
    LOGIN_ERROR, REGISTER_ERROR,
    PARAMETERS_MISSING, EXPIRED_SESSION,
    CREATE_USER_ERROR, HOME_PAGE_ERROR,
    DISCONNECTED_RESPONSE, DB_ERROR,  IMAGE_NOT_FOUND,
    COMMENT_NOT_FOUND, IMAGE_CREATED_FAILED,
    COMMENT_CREATION_FAILED, ALREADY_DELETED,
    NOT_AUTHORIZED, NO_UPDATES, INVALID,
    NOT_FOUND, SERVER_ERROR, UPDATE_SECONDS,
};